name: Push workflow for flap
on:
  push:
    branches:
      - "*"

jobs:
  check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup golang with 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16

      - name: Run golang test
        run: go test ./... -v -cover